config/routes.rb
Rails.application.routes.draw do
  resources :anwsers
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/anwsers/:question_id/new', to: 'anwsers#new'

  root to: 'application#index'
end

app/models/anwser.rb
class Anwser < ApplicationRecord
    validates_presence_of :content, :question, :user

    belongs_to :question
    belongs_to :user
    has_many :votes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates_presence_of :title, :content, :user

    belongs_to :user
    has_many :anwsers

    scope :my_questions, -> { order('questions.created_at DESC').limit(3) }
end

app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :email, :name

    has_many :questions
    has_many :anwsers
    has_many :votes

    def self.find_or_create_from_auth_hash(oauth_hash)
        user = User.find_by(:email => oauth_hash['info']['email']);

        if !user
            user = User.new
            user.name = oauth_hash['info']['name']
            user.email = oauth_hash['info']['email']
            user.image_url = oauth_hash['info']['image']

            user.save
        end
        
        user
    end
end

app/controllers/anwsers_controller.rb
class AnwsersController < ApplicationController
  before_action :set_anwser, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :edit, :update, :destroy]

  # GET /anwsers/new
  def new
    @anwser = Anwser.new
    @anwser.question_id = params['question_id']
    session['question_id'] = params['question_id']
  end

  # GET /anwsers/1/edit
  def edit
  end

  # POST /anwsers
  # POST /anwsers.json
  def create
    @anwser = Anwser.new(anwser_params)

    @anwser.question_id = session['question_id']
    @anwser.user = current_user
    session['question_id'] = nil

    respond_to do |format|
      if @anwser.save
        format.html { redirect_to @anwser.question, notice: 'Anwser was successfully created.' }
        format.json { render :show, status: :created, location: @anwser }
      else
        format.html { render :new }
        format.json { render json: @anwser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anwsers/1
  # PATCH/PUT /anwsers/1.json
  def update
    respond_to do |format|
      if @anwser.update(anwser_params)
        format.html { redirect_to @anwser.question, notice: 'Anwser was successfully updated.' }
        format.json { render :show, status: :ok, location: @anwser }
      else
        format.html { render :edit }
        format.json { render json: @anwser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anwsers/1
  # DELETE /anwsers/1.json
  def destroy
    question = @anwser.question
    @anwser.destroy
    respond_to do |format|
      format.html { redirect_to question, notice: 'Anwser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anwser
      @anwser = Anwser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anwser_params
      params.require(:anwser).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def initialize
    super
    @user_service = UserService.new
  end

  def index
  end

  def current_user
    @current_user ||= @user_service.find(session['user_id']) if session['user_id']
  end

  def logged_in?
    if current_user != nil
      true
    else
      false
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = "Voce precisa estar autenticado"
      redirect_to '/'
    end
  end

  helper_method :current_user, :logged_in?, :require_login

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.includes(:anwsers, :user).all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    hits = @question.hits.to_i
    hits = hits + 1
    @question.hits = hits
    @question.save
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy

    @question.anwsers.each do |a|
      a.destroy
    end

    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.includes(:anwsers, :user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  def initialize
    @user_service = UserService.new
  end

  def create
      @user = @user_service.oauth_login(auth_hash)
      session['user_id'] = @user.id
      redirect_to '/'
    end

    def logout
      session['user_id'] = nil
      redirect_to '/'
    end
  
    protected
  
    def auth_hash
      request.env['omniauth.auth']
    end

  end

app/helpers/anwsers_helper.rb
module AnwsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/anwsers/_form.html.erb
<%= form_for @anwser, :html => { :class => "form-horizontal anwser" } do |f| %>

  <% if @anwser.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@anwser.errors.count, "error") %> prohibited this anwser from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @anwser.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                "/questions/#{@anwser.question_id}", :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/anwsers/edit.html.erb
<%- model_class = Anwser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/anwsers/index.html.erb
<%- model_class = Anwser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:question_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @anwsers.each do |anwser| %>
      <tr>
        <td><%= link_to anwser.id, anwser_path(anwser) %></td>
        <td><%= anwser.content %></td>
        <td><%= anwser.question_id %></td>
        <td><%= anwser.user_id %></td>
        <td><%=l anwser.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      anwser_path(anwser), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_anwser_path(anwser), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      anwser_path(anwser),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_anwser_path,
            :class => 'btn btn-primary' %>

app/views/anwsers/new.html.erb
<%- model_class = Anwser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/application/index.html.erb
<h1>Home</h1>
<% if current_user %>
    <h3>Bem vindo, <%= current_user['name'] %> </h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Stack</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Question", questions_url  %></li>

            <% if current_user %>
                <li><%= link_to "Sair", href="/logout" %></li>
            <% else %>
                <li><%= link_to "Entrar", href="/auth/github" %></li>
            <% end %>
            
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
      <div class="col-lg-3">

          <div class="well sidebar-nav">
            <h3>Minhas Perguntas</h3>
            <ul class="nav nav-list">

              <% if current_user %>
                <% current_user.questions.my_questions.each do |q| %>
                  <li><%= link_to q.title, q  %></li>
                <% end %>
              <% else %>
                  <li><%= link_to "Entrar", href="/auth/github" %></li>
              <% end %>
              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => "form-horizontal question" } do |f| %>

  <% if @question.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:hits) %></th>
      <th><%= model_class.human_attribute_name(:anwsers) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.title, question_path(question) %></td>
        <td><%= question.hits.to_i %></td>
        <td><%= question.anwsers.count.to_i %></td>
        <td><%= question.content %></td>
        <td><%= question.user.name %></td>
        <td><%=l question.created_at, :format => '%d/%m/%Y' %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      question_path(question), :class => 'btn btn-default btn-xs' %>
          <% if current_user == question.user %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_question_path(question), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        question_path(question),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%= @question.title %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:hits) %>:</strong></dt>
  <dd><%= @question.hits.to_i %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @question.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @question.user.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn btn-default'  %>

<% if current_user == @question.user %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_question_path(@question), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                question_path(@question),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>
<% if @question.anwsers.count > 0 %>
  <h3>Respostas</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:content) %></th>
        <th><%= model_class.human_attribute_name(:question_id) %></th>
        <th><%= model_class.human_attribute_name(:user_id) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <% if current_user %>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @question.anwsers.each do |anwser| %>
        <tr>
          <td><%= anwser.content %></td>
          <td><%= anwser.question_id %></td>
          <td><%= anwser.user.name %></td>
          <td><%=l anwser.created_at, :format => '%d/%m/%Y' %></td>
          <% if current_user %>
            <td>
              <% if current_user == @question.user || current_user == anwser.user %>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_anwser_path(anwser), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            anwser_path(anwser),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              <% end %>            
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<div>
  <div class="response">
    <% if current_user %>
    <%= link_to "Responder", "/anwsers/#{@question.id}/new", :class => 'btn btn-default' %>
    <% end %>
  </div>
</div>